### PR TITLE
accept .dist files as json or yaml

### PR DESCRIPTION
**Pull request by tim-heinsohn**
A proposal to accept common files like `config.json.dist` or `settings.yml.dist` without throwing an Exception.

### CODE REVIEW

**Comment by igorw** [comment]
Is there any project using `.yaml` as an extension? Unless this is common, I'd rather it stays just `.yml`.

Apart from that, I like it.

**Comment by tim-heinsohn** [comment]
> Is there any project using .yaml as an extension? Unless this is common, I'd rather it stays just `.yml`.

I don't know of any, and as part of the Symfony ecosystem it probably makes sense to stick with `.yml` as default. So I'll revert that change, but wouldn't take it out completely. At least at #yaml (Freenode) there are people prefering `.yaml`, see [this project](https://bitbucket.org/prometheus/htsql/src/301278145fd9/test/output) for example.

> Apart from that, I like it.

Nice :)

**Comment by tim-heinsohn** [comment]
I'm ready to push, yet: `getFileFormat()` does not return the file ending but the actual _format_, which should be "YAML" (see [yaml.org](http://yaml.org/)). So the default is not about file endings, just about what they contain and both file endings are supported by the code. I'd keep it as it is or maybe even use a constant (a bit over-engineered, yes) to clarify things. What do you think? Same for "JSON".

**Comment by igorw** [comment]
Keep it simple. I'm fine with supporting both .yml and .yaml. Will adjust the patch and merge.

**Comment by igorw** [comment]
Merged with some amendments: ca8b3710cc3a6a397ec42d8163766920e90c920a.

**Pull request merged**
