### PR TITLE
Require Pimple 3.0 instead of whole of Silex

### PR DESCRIPTION
**Pull request by henrikbjorn**

### CODE REVIEW

**Comment by henrikbjorn** [comment]
Dont know if you want to change the namespace, as it currently contains "Silex" in its name.

**Comment by Seldaek** [comment]
:+1:

**Comment by dominikzogg** [comment]
@henrikbjorn Good idea but i see some problems with this PR
- please use `>=2.1,4` als pimple requirement
- ~~psr-4 got no benefit in a project like this~~
- ~~tests still based on silex~~

My fault, did not read carefull enough (tests)

**Comment by henrikbjorn** [comment]
@dominikzogg the 2.x versions are confused and contain a file that class_aliases Pimple to Container, and for that reason it will not work with the extension. So 3.0 is the correct version

**Comment by kingcrunch** [comment]
:+1:

**Comment by dominikzogg** [comment]
@igorw would be cool, if you would merge this

**Comment by simplechris** [comment]
+1 on merging this

**Comment by dominikzogg** [comment]
i use my fork, i hope you will join, your PR is already within master, v1 is for silex ~1.3

**Pull request closed without merging**
