### PR TITLE
Replacements in config.

### PR DESCRIPTION
**Pull request by marcinkleczek**
This patch allow to define replacements in config file:

YAML:
%app.path%: "d:\dbaltest"
monolog.logfile: "%app.path%/logs/debug.log"

### CODE REVIEW

**Comment by igorw** [comment]
That's pretty cool, please add some tests.

**Comment by marcinkleczek** [comment]
Igor, please check the tests.

**Comment by igorw** [comment]
Looks good. Now it just needs to be documented in the README.

**Comment by marcinkleczek** [comment]
I'm sorry, but my English is weak - too weak to write documentation.

**Comment by igorw** [comment]
Thanks, merged, added docs to README and tagged v1.1.1.

**Pull request merged**
