### PR TITLE
Yaml imports support

### PR DESCRIPTION
**Pull request by Devolicious**
Using a yaml config file, you will be able to import resources instead of reinstantiating the ConfigServiceProvider for multiple config files.

### CODE REVIEW

**Comment by StanAngeloff** [comment]
Trivial comment: I have a similar implementation and ran into issues when the team was using it. Because the `imports` were at the top of the file, the feeling was that they will be pulled before the rest of the file is loaded. This did cause some confusion and at the end I had to put a check that the last key in the array is `imports` so that those are always defined at the end of a YAML file.

``` yml
# Nope, file1.yml will not act as defaults and will, instead,
#   override any properties defined here. Exception is thrown.
imports:
  - file1.yml

property: value
```

---

``` yml
property: value

# Imports are at the end of the file. Values will override defaults defined above.
imports:
  - file1.yml
```

Glad your implementation has accounted for this :smile:

Can a suggest a sentence in the documentation is added to state the fact `imports` are processed before the `.yml` they are defined in?

**Comment by igorw** [comment]
I intentionally left this out. I want features to be consistently supported by all formats, and I don't really want the added complexity of doing imports right (with recursion detection, etc).

I will think about this a bit, but I will likely not accept this feature, sorry.

**Comment by Devolicious** [comment]
Maybe I should call it "extend" or "inherit" because in my setup the import will be overridden with the configuration from the file it is imported. That name change will also sort out the confusion StanAngloff is talking about. It is logic that the properties you extend will be overridden when set in the child config file.

And it doens't have to be a yaml only option :)

**Comment by igorw** [comment]
I decided to close this, sorry :)

**Pull request closed without merging**
